-- ----------------------------------------------------------------------------
-- Put here INSERT statements for inserting data required by the application
-- in the "pa-project" database.
-------------------------------------------------------------------------------

INSERT INTO Food_Group VALUES(1,'DESCRIPTION1',0);
INSERT INTO Food_Group VALUES(2,'DESCRIPTION2',1);
INSERT INTO Food_Group VALUES(3,'DESCRIPTION3',2);
INSERT INTO Food_Group VALUES(4,'DESCRIPTION4',3);
INSERT INTO Food_Group VALUES(5,'DESCRIPTION5',4);
INSERT INTO Food_Group VALUES(6,'DESCRIPTION6',5);
INSERT INTO Food_Group VALUES(7,'DESCRIPTION7',6);
INSERT INTO Food_Group VALUES(8,'DESCRIPTION8',7);
INSERT INTO Food_Group VALUES(9,'DESCRIPTION9',8);
INSERT INTO Food_Group VALUES(10,'DESCRIPTION10',9);
INSERT INTO Food_Group VALUES(11,'DESCRIPTION11',10);
INSERT INTO Food_Group VALUES(12,'DESCRIPTION12',11);
INSERT INTO Food_Group VALUES(13,'DESCRIPTION13',12);

INSERT INTO Recipe_Group VALUES(1,'DESCRIPTION1',0);
INSERT INTO Recipe_Group VALUES(2,'DESCRIPTION2',1);
INSERT INTO Recipe_Group VALUES(3,'DESCRIPTION3',2);
INSERT INTO Recipe_Group VALUES(4,'DESCRIPTION4',3);
INSERT INTO Recipe_Group VALUES(5,'DESCRIPTION5',4);
INSERT INTO Recipe_Group VALUES(6,'DESCRIPTION6',5);
INSERT INTO Recipe_Group VALUES(7,'DESCRIPTION7',6);
INSERT INTO Recipe_Group VALUES(8,'DESCRIPTION8',7);
INSERT INTO Recipe_Group VALUES(9,'DESCRIPTION9',8);
